nodeLinker: node-modules
# nodeLinker: pnp
# Use a built-in resolver to resolve modules
# This is necessary when using PnP
# pnpStrategy: "auto"

# Disable the built-in cache and use the default Node.js cache
# cache: false
# yarnPath: .yarn/releases/yarn-3.5.0.cjs
